# Generated by Django 2.0 on 2017-12-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency', '0002_auto_20171213_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='date',
            new_name='datetime',
        ),
    ]
